name: windows workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: windows-latest
    steps:
      - name: Print Hello
        run: echo "Hello World Action"
      - name: Print bye
        run: echo "bye bye"
